source 'https://rubygems.org'

gem "blobsterix"

group :development do
  gem "pry"
  gem "capistrano", "2.15.4"
  gem "capistrano-ext", "1.2.1"
  gem "rvm-capistrano", "~> 1.5.1"
  gem "railsless-deploy", :require => false
end
