AllCops:
  Exclude:
    - 'templates/**/*'

Metrics/LineLength:
  Max: 99

Style/AlignHash:
  EnforcedHashRocketStyle: table

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/RegexpLiteral:
  Enabled: false
Style/PerlBackrefs:
  Enabled: false
Style/StringLiterals:
  Enabled: false

